const temp = [
  {
    id: 1,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design'],
    projectTitle: "Bank of Maharashtra Perundurai, Chennai Zone,perunthurai",
    title: "Bank of Maharashtra Perundurai" ,
  },
  {
    id: 2,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design'],
    projectTitle: "Bank of Maharashtra  Perundurai, Chennai Zone,porur,",
    title: "Bank of Maharashtra Porur" ,
  },
  {
    id: 3,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design'],
    projectTitle: "Bank of Maharashtra  Chennai Zone,,Tiruvallur,",
    title: "Bank of Maharashtra Tiruvallur" ,
  },
  {
    id: 4,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design'],
    projectTitle: "Bank of Maharashtra  Chennai Zone,,Marthandam,",
    title: "Bank of Maharashtra Marthandam" ,
  },
  {
    id: 5,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Fit Out & Interior Design'],
    projectTitle: "Bank of Maharashtra, Kelambakkam Chennai",
    title: "Bank of Maharashtra Kelambakkam",
  },
  {
    id: 6,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Structural Engineering'],
    projectTitle: "HITES- kerala",
    title: "HITES Kerala" ,
  },
  {
    id: 7,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Structural Engineering', 'Project Management Consultancy', 'Environmental Solutions', 'Landscaping', 'Fit Out & Interior Design'],
    projectTitle: "Paradip Port Authority -Odisha",
    title: "Paradip Port Authority",
  },
  {
    id: 8,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Fit Out & Interior Design'],
    projectTitle: "SIDBI Branch Office at Bangalore",
    title: "SIDBI Branch Bangalore",
  },
  {
    id: 9,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Fit Out & Interior Design'],
    projectTitle: "SIDBI Branch Office at Ambattur",
    title: "SIDBI Branch Ambattur" ,
  },
  {
    id: 10,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Fit Out & Interior Design'],
    projectTitle: "SIDBI Branch Office at Hosur",
    title: "SIDBI Branch Hosur" ,
  },
  {
    id: 11,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Fit Out & Interior Design'],
    projectTitle: "SIDBI Branch Office at Korattur",
    title: "SIDBI Branch Korattur" ,
  },
  {
    id: 12,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Fit Out & Interior Design'],
    projectTitle: "United Insurance of India T.Nagar,Chennai",
    title: "United Insurance T.Nagar",
  },
  {
    id: 13,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: [],
    projectTitle: "Venjaramoodu Branch office-Kerala",
    title: "Venjaramoodu Branch Office",
  },
  {
    id: 14,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Structural Engineering'],
    projectTitle: "AROOR GRAMA PANCHAYATH SHOPPING COMPLEX-Kerala",
    title: "AROOR Shopping Complex",
  },
  {
    id: 15,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Environmental Solutions'],
    projectTitle: "Freshwater Aquapark at Kannur, kerala",
    title: "Freshwater Aquapark Kannur",
  },
  {
    id: 16,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Environmental Solutions', 'Landscaping'],
    projectTitle: "Beach Front Neelankarai to Akkarai",
    title: "Beach Front Neelankarai",
  },
  {
    id: 17,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Environmental Solutions', 'Landscaping'],
    projectTitle: "Beach Front  Thiruvottriyur”",
    title: "Beach Front Thiruvottriyur",
  },
  {
    id: 18,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Environmental Solutions', 'Landscaping'],
    projectTitle: "Lakefront kolathur,chennai",
    title: "Lakefront Kolathur",
  },
  {
    id: 19,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "Ennore community Hall-CHENNAI",
    title: "Ennore Community Hall",
  },
  {
    id: 20,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "GCC School at Allapakkam, Chennai",
    title: "GCC School Allapakkam",
  },
  {
    id: 21,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "GCC Begam school , chennai",
    title: "GCC Begam School",
  },
  {
    id: 22,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "GCC MMDA School,chennai",
    title: "GCC MMDA School",
  },
  {
    id: 23,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "GCC Nolambur School,chennai",
    title: "GCC Nolambur School",
  },
  {
    id: 24,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "GCC Rama Street School,chennai",
    title: "GCC Rama Street School",
  },
  {
    id: 25,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "GCC sathunavu Koodam School,,chennai",
    title: "GCC Sathunavu Koodam School",
  },
  {
    id: 26,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "Pammal community Hall,chennai",
    title: "Pammal Community Hall" ,
  },
  {
    id: 27,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "Pammal Municipality schools,chennai",
    title: "Pammal Municipality Schools",
  },
  {
    id: 28,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Structural Engineering'],
    projectTitle: "JIMPER HOSIPTAL -Pondicherry",
    title: "JIMPER Hospital Pondicherry",
  },
  {
    id: 29,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "Over Head Tank at Kundrathur,Bazar Street ,chennai",
    title: "Over Head Tank Kundrathur" ,
  },
  {
    id: 30,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'Structural Engineering'],
    projectTitle: "Over Head Tank at Kundrathur, Bazar Street ,chennai",
    title: "Over Head Tank Kundrathur" ,
  },
  {
    id: 31,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Environmental Solutions'],
    projectTitle: "Thanjavur smart city projects,Thanjavur",
    title: "Thanjavur Smart City Projects",
  },
  {
    id: 32,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Environmental Solutions'],
    projectTitle: "Thanjavur smart city Phase 3 development,Thanjavur",
    title: "Thanjavur Smart City Phase 3",
  },
  {
    id: 33,
    imageSrc: "/assets/img/portfolio/portfolio4_6.png",
    categoryLinks: ['Architecture & Design', 'MEP Design', 'Structural Engineering', 'Environmental Solutions', 'Landscaping'],
    projectTitle: "Turtle Building,Chennai",
    title: "Turtle Building Chennai,"
  }
]